rule create_db:
    input:
        "input/Food_Inspections_50k.csv"
    output:
        "assignment3.db"
    shell:
        "sqlite3 assignment3.db < input/create_and_load_db.sql"

rule aggregate_sql:
    input:
        "assignment3.db"
    output:
        "results/sql-fac-types.csv"
    shell:
        "sqlite3 assignment3.db < aggregate.sql"

rule aggregate_pandas:
    input:
        "input/Food_Inspections_50k.csv"
    output:
        "results/pandas-fac-types.csv"
    shell:
        "python3 aggregate.py"

rule compare:
    input:
        "results/pandas-fac-types.csv",
        "results/sql-fac-types.csv"
    output:
        "results/comparison.csv"
    shell:
        "python3 compare.py"

